# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Accounts Manager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Accounts Manager
  pod 'DropDown'
  pod 'RealmSwift'

  target 'Accounts ManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Accounts ManagerUITests' do
    # Pods for testing
  end

end
